import {test,expect} from '@playwright/test';
async function register(page,{name,phone,role}){
 await page.goto('/');await page.locator('#profile').click();await page.locator('#auth-switch').click();
 await page.locator('[name=name]').fill(name);await page.locator('[name=age]').fill('35');await page.locator('[name=role]').selectOption(role);await page.locator('[name=address]').fill('Solapur farm road');await page.locator('[name=phone]').fill(phone);await page.locator('[name=password]').fill('Farm-password-123');await page.locator('#auth-form button[type=submit]').click();await expect(page.locator('#modal-root')).toBeEmpty();
}
test('provider publishes a team, farmer uses GPS and books, provider accepts, farmer cancels',async({browser})=>{
 const providerContext=await browser.newContext({permissions:['geolocation'],geolocation:{latitude:17.66,longitude:75.91}});const farmerContext=await browser.newContext({viewport:{width:390,height:844},permissions:['geolocation'],geolocation:{latitude:17.65,longitude:75.9}});
 const provider=await providerContext.newPage(),farmer=await farmerContext.newPage();const errors=[];provider.on('pageerror',e=>errors.push(e.message));farmer.on('pageerror',e=>errors.push(e.message));
 await register(provider,{name:'Local Provider',phone:'9111111111',role:'provider'});await provider.locator('#profile').click();await provider.locator('#manage-team').click();
 await provider.locator('[name=name]').fill('Solapur Harvest Team');await provider.locator('[name=place]').fill('North Solapur');await provider.locator('[name=crops]').selectOption(['Grape']);await provider.locator('[name=skills]').fill('Harvesting, Pruning');await provider.locator('[name=people]').fill('5');await provider.locator('[name=price]').fill('450');await provider.locator('[name=lat]').fill('17.65');await provider.locator('[name=lng]').fill('75.9');await provider.locator('#team-form [name=name]').fill('Solapur Harvest Team');await expect(provider.locator('#team-form [name=name]')).toHaveValue('Solapur Harvest Team');await provider.locator('#team-form button[type=submit]').click();await expect(provider.locator('#modal-root')).toBeEmpty();await expect(provider.locator('.team-title')).toContainText('Solapur Harvest Team');
 await register(farmer,{name:'Farmer Ramesh',phone:'9222222222',role:'farmer'});await farmer.locator('#location').click();await farmer.locator('#use-gps').click();await expect(farmer.locator('#modal-root')).toBeEmpty();await expect(farmer.locator('.team-location')).toContainText('0 km away');
 await farmer.locator('[data-crop=Grape]').click();await farmer.locator('[data-book]').click();await farmer.locator('[name=workers]').fill('3');const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());await farmer.locator('[name=date]').fill(date);await farmer.locator('[name=address]').fill('Ramesh farm, near village school');await farmer.locator('#booking-form button[type=submit]').click();await expect(farmer.locator('.booking-row')).toContainText('Waiting for provider');await expect(farmer.locator('.booking-row')).toContainText('1,350');
 await provider.locator('[data-view=bookings]').click();await expect(provider.locator('.booking-row')).toContainText('Farmer Ramesh');await provider.locator('[data-status=accepted]').click();await expect(provider.locator('.pending')).toHaveText('Confirmed');await provider.locator('[data-share]').click();await expect(provider.locator('[data-share]')).toHaveText('Stop sharing my GPS');
 await farmer.locator('#refresh-bookings').click();await expect(farmer.locator('.pending')).toHaveText('Confirmed');await expect(farmer.locator('.gps-map-link')).toHaveAttribute('href',/17\.66%2C75\.91/);await expect(farmer.locator('.gps-last-update')).toContainText('Last team GPS update');await farmer.screenshot({path:'artifacts/farmer-booking.png',fullPage:true});
 await farmer.locator('[data-status=cancelled]').click();await expect(farmer.locator('.pending')).toHaveText('Cancelled');await expect(farmer.locator('.gps-map-link')).toHaveCount(0);await provider.locator('#refresh-bookings').click();await expect(provider.locator('.pending')).toHaveText('Cancelled');
 expect(errors).toEqual([]);await providerContext.close();await farmerContext.close();
});
