import {api,esc} from './api.js';
const root=document.querySelector('#admin-app');
let user=null,section='overview',records={counts:{},users:[],teams:[],bookings:[],events:[],admins:[]},busy=false,notice='';
const labels={overview:'Overview',users:'People',teams:'Labour teams',bookings:'Bookings',audit:'Activity log',admins:'Admin accounts'};
const icon={overview:'▦',users:'♙',teams:'♧',bookings:'▤',audit:'◷',admins:'⚙'};
const status=x=>({pending:'Waiting',accepted:'Confirmed',declined:'Declined',cancelled:'Cancelled',completed:'Completed'}[x]||x);
function flash(message){notice=message;render();setTimeout(()=>{notice='';render();},4500);}
function showError(e){flash(e.message||String(e));}
function login(){root.innerHTML=`<div class="login-shell"><div class="login-panel"><div class="logo"><span>✳</span> Krishi Saathi</div><div class="kicker">KVK SOLAPUR-I · OPERATIONS</div><h1>Admin sign in</h1><p>Manage farmers, providers and labour bookings from one place.</p><form id="login-form"><label>Admin mobile number<input name="phone" type="tel" inputmode="numeric" pattern="[6-9][0-9]{9}" maxlength="10" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><div class="error" id="login-error" role="alert"></div><button class="primary">Sign in to admin</button></form><a href="/">← Back to farmer app</a></div></div>`;root.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const result=await api('/admin/login',{method:'POST',body:Object.fromEntries(new FormData(e.target))});sessionStorage.setItem('krishi-token',result.token);user=result.user;if(user.mustChangePassword)passwordChange();else await load();}catch(error){root.querySelector('#login-error').textContent=error.message;button.disabled=false;}};}
function passwordChange(){root.innerHTML=`<div class="login-shell"><div class="login-panel"><div class="logo"><span>✳</span> Krishi Saathi</div><div class="kicker">ACCOUNT SECURITY</div><h1>Change temporary password</h1><p>Set a private password before opening admin records.</p><form id="change-form"><label>Temporary password<input name="currentPassword" type="password" autocomplete="current-password" required></label><label>New password<input name="newPassword" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><label>Repeat new password<input name="confirm" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><div class="error" id="change-error" role="alert"></div><button class="primary">Save new password</button></form></div></div>`;root.querySelector('#change-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(data.newPassword!==data.confirm){root.querySelector('#change-error').textContent='Passwords do not match.';return;}const button=e.target.querySelector('button');button.disabled=true;try{user=(await api('/admin/password',{method:'PATCH',body:{currentPassword:data.currentPassword,newPassword:data.newPassword}})).user;await load();}catch(error){root.querySelector('#change-error').textContent=error.message;button.disabled=false;}};}
async function load(){try{const [overview,users,teams,bookings,audit,admins]=await Promise.all([api('/admin/overview'),api('/admin/users'),api('/admin/teams'),api('/admin/bookings'),api('/admin/audit'),api('/admin/admins')]);records={counts:overview.counts,users:users.users,teams:teams.teams,bookings:bookings.bookings,events:audit.events,admins:admins.admins};render();}catch(e){if(e.status===401){user=null;login();}else showError(e);}}
const badge=(value,cls='')=>`<span class="pill ${cls}">${esc(value)}</span>`;
function overview(){const c=records.counts;return `<div class="stats">${[['Farmers',c.farmers],['Labour providers',c.providers],['Listed teams',c.teams],['Pending bookings',c.pendingBookings],['Unverified teams',c.unverifiedTeams],['Confirmed bookings',c.acceptedBookings]].map(([label,num])=>`<div class="stat"><span>${label}</span><strong>${num??0}</strong></div>`).join('')}</div><div class="intro"><h2>KVK operations</h2><p>Review new labour teams, help farmers resolve booking issues, and keep account access up to date. Every admin action is recorded in the activity log.</p><div class="quick"><button data-section="teams">Review teams →</button><button data-section="bookings">Review bookings →</button><button data-section="users">Manage people →</button></div></div>`;}
function users(){return `<div class="panel"><div class="panel-top"><h2>Farmers and providers</h2><span>${records.users.length} accounts</span></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Phone</th><th>Village / farm</th><th>Access</th><th>Action</th></tr></thead><tbody>${records.users.map(u=>`<tr><td><strong>${esc(u.name)}</strong><small>#${u.id}</small></td><td>${badge(u.role)}</td><td>${esc(u.phone)}</td><td>${esc(u.address)}</td><td>${badge(u.suspended?'Suspended':'Active',u.suspended?'red':'green')}</td><td><button class="small ${u.suspended?'positive':'danger'}" data-user="${u.id}" data-suspend="${!u.suspended}">${u.suspended?'Restore access':'Suspend access'}</button></td></tr>`).join('')}</tbody></table></div>${records.users.length?'':'<p class="empty">No accounts registered yet.</p>'}</div>`;}
function teams(){return `<div class="panel"><div class="panel-top"><h2>Labour teams</h2><span>${records.teams.length} teams</span></div><div class="table-wrap"><table><thead><tr><th>Team</th><th>Provider</th><th>Workers & rate</th><th>Skills</th><th>Verification</th><th>Listing</th></tr></thead><tbody>${records.teams.map(t=>`<tr><td><strong>${esc(t.name)}</strong><small>${esc(t.place)}</small></td><td>${esc(t.providerName)}<small>${esc(t.providerPhone)}</small></td><td>${t.people} · ₹${t.price}/day</td><td>${t.skills.map(esc).join(', ')}</td><td>${badge(t.verified?'Verified':'Needs review',t.verified?'green':'amber')}<br><button class="small" data-team="${t.id}" data-verified="${!t.verified}">${t.verified?'Remove verification':'Mark verified'}</button></td><td>${badge(t.adminHidden?'Hidden':t.providerSuspended?'Provider suspended':t.available?'Visible':'Provider unavailable',t.adminHidden||t.providerSuspended?'red':'green')}<br><button class="small" data-team="${t.id}" data-hidden="${!t.adminHidden}">${t.adminHidden?'Show listing':'Hide listing'}</button></td></tr>`).join('')}</tbody></table></div>${records.teams.length?'':'<p class="empty">No provider teams yet.</p>'}</div>`;}
function bookings(){return `<div class="panel"><div class="panel-top"><h2>All bookings</h2><span>${records.bookings.length} requests</span></div><div class="table-wrap"><table><thead><tr><th>Booking</th><th>Farmer</th><th>Team / provider</th><th>Work</th><th>Date</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>${records.bookings.map(b=>`<tr><td>#${b.id}</td><td><strong>${esc(b.farmerName)}</strong><small>${esc(b.farmerPhone)}</small><small>${esc(b.address)}</small></td><td>${esc(b.team)}<small>${esc(b.providerName)} · ${esc(b.providerPhone)}</small></td><td>${esc(b.task)}<small>${b.workers} workers</small></td><td>${esc(b.date)}</td><td>₹${b.total.toLocaleString('en-IN')}</td><td>${badge(status(b.status),b.status==='accepted'?'green':b.status==='pending'?'amber':b.status==='cancelled'?'red':'')}</td><td>${['pending','accepted'].includes(b.status)?`<button class="small danger" data-cancel="${b.id}">Cancel</button>`:''}</td></tr>`).join('')}</tbody></table></div>${records.bookings.length?'':'<p class="empty">No booking requests yet.</p>'}</div>`;}
function audit(){return `<div class="panel"><div class="panel-top"><h2>Admin activity</h2><span>Latest 100 actions</span></div><div class="table-wrap"><table><thead><tr><th>When</th><th>Admin</th><th>Action</th><th>Record</th><th>Detail</th></tr></thead><tbody>${records.events.map(e=>`<tr><td>${esc(e.createdAt)}</td><td>${esc(e.adminName)}</td><td>${badge(e.action.replaceAll('_',' '))}</td><td>${esc(e.targetType)} #${e.targetId}</td><td>${esc(e.detail||'—')}</td></tr>`).join('')}</tbody></table></div>${records.events.length?'':'<p class="empty">Admin actions will appear here.</p>'}</div>`;}
function admins(){return `<div class="admin-grid"><div class="panel"><div class="panel-top"><h2>KVK administrators</h2><span>${records.admins.length} admins</span></div><div class="admin-rows">${records.admins.map(a=>`<div><strong>${esc(a.name)}</strong><span>${esc(a.phone)} · ${a.mustChangePassword?'Temporary password':'Active login'}</span></div>`).join('')}</div></div><div class="panel new-admin"><h2>Add a KVK admin</h2><p>They must change their temporary password at first login.</p><form id="new-admin"><label>Name<input name="name" required minlength="2"></label><label>Mobile number<input name="phone" required pattern="[6-9][0-9]{9}" maxlength="10"></label><label>Temporary password<input name="password" type="password" required minlength="12" maxlength="128"></label><button class="primary">Create admin</button></form></div></div>`;}
function render(){if(!user)return login();if(user.mustChangePassword)return passwordChange();root.innerHTML=`<div class="admin-layout"><aside><a href="/admin" class="logo"><span>✳</span><div>Krishi Saathi<small>KVK ADMIN</small></div></a><nav>${Object.keys(labels).map(key=>`<button data-section="${key}" class="${section===key?'active':''}"><span>${icon[key]}</span>${labels[key]}</button>`).join('')}</nav><div class="aside-foot"><strong>${esc(user.name)}</strong><small>${esc(user.phone)}</small><button id="change-password">Change password</button><button id="signout">Sign out</button></div></aside><div class="main"><header><div><div class="eyebrow">KVK SOLAPUR-I · KRISHI SAATHI</div><h1>${labels[section]}</h1><p>Manage the people and work behind every farm request.</p></div><button id="refresh">↻ Refresh data</button></header><main>${({overview,users,teams,bookings,audit,admins})[section]()}</main>${notice?`<div class="toast" role="status">${esc(notice)}</div>`:''}</div></div>`;bind();}
async function action(run){if(busy)return;busy=true;try{await run();await load();}catch(e){showError(e);}finally{busy=false;}}
function bind(){root.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;render();});root.querySelector('#refresh').onclick=load;root.querySelector('#signout').onclick=async()=>{try{await api('/auth/logout',{method:'POST',body:{}});}catch{}sessionStorage.removeItem('krishi-token');user=null;login();};root.querySelector('#change-password').onclick=()=>passwordChange();
root.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{const suspend=b.dataset.suspend==='true';if(!confirm(`${suspend?'Suspend':'Restore'} this account?`))return;action(()=>api(`/admin/users/${b.dataset.user}`,{method:'PATCH',body:{suspended:suspend}}));});
root.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{const verifying=b.dataset.verified!==undefined,enabled=(verifying?b.dataset.verified:b.dataset.hidden)==='true';const description=verifying?'verification':'listing visibility';if(!confirm(`Change ${description} for this team?`))return;action(()=>api(`/admin/teams/${b.dataset.team}`,{method:'PATCH',body:verifying?{verified:enabled}:{adminHidden:enabled}}));});
root.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{const reason=prompt('Why is KVK cancelling this booking? The reason will be saved in the admin activity log.');if(reason===null)return;action(()=>api(`/admin/bookings/${b.dataset.cancel}/cancel`,{method:'POST',body:{reason}}));});
const form=root.querySelector('#new-admin');if(form)form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));if(!confirm(`Create admin ${data.name} for ${data.phone}?`))return;action(()=>api('/admin/admins',{method:'POST',body:data}));};}
async function boot(){if(!sessionStorage.getItem('krishi-token'))return login();try{user=(await api('/me')).user;if(user.role!=='admin'){sessionStorage.removeItem('krishi-token');user=null;return login();}if(user.mustChangePassword)return passwordChange();await load();}catch{sessionStorage.removeItem('krishi-token');user=null;login();}}
boot();
